schedule: &schedule
  interval: "weekly"
  day: "saturday"
  timezone: "Asia/Tokyo"

version: 2
updates:
- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    <<: *schedule
  open-pull-requests-limit: 10
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    <<: *schedule
