version: 2
updates:
- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "monthly"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 30
# - package-ecosystem: "npm"
#   directory: "/"
#   schedule:
#     interval: "weekly"
#     day: "saturday"
#     timezone: "Asia/Tokyo"
#   open-pull-requests-limit: 10
