require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rubycw

inherit_mode:
  merge:
    - Include

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  CacheRootDirectory: './tmp/cache'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# Disable trailing blank lines in app/models/*.rb due to schema annotation comments.
Layout/TrailingEmptyLines:
  Exclude:
    - 'app/models/**/*.rb'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Lint/AmbiguousBlockAssociation:
  Enabled: true
  Exclude:
    - 'spec/**/*_spec.rb'

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - class_methods
    - concerning

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'app/services/new_episode_checker.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'app/services/new_episode_checker.rb'

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'config/initializers/*.rb'
    - 'lib/tasks/wikipedia.rake'

Style/Documentation:
  Exclude:
    - 'config/**/*.rb'

Style/EmptyElse:
  EnforcedStyle: empty

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$RESERVED_USERNAMES]

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Exclude:
    - 'app/graphql/**/*.rb' # Allow multiline arrow funciton within GraphQL schema

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
