services:
  - type: web
    name: jrnl
    plan: free
    env: ruby
    repo: https://github.com/juno/jrnl.git
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    domains:
      - journal.sooey.com
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false # Set Neon's DB connection string on Web UI
      - key: SECRET_KEY_BASE
        sync: false
      - key: WEB_CONCURRENCY
        value: 1
      - key: RAILS_MAX_THREADS
        value: 2

