defaults: &defaults
  caching:
    use: false

  author:
    name: Junya Ogura
    email: juno at sooey.com

  social:
    - name: profile
      url: https://junya.bio.link/

  feedburner:
    use: true
    url: http://feeds.feedburner.com/Sooey

  twitter_anywhere:
    use: false
    id: ua931JjzNdqgvz2B0S85jA

development:
  <<: *defaults

test:
  <<: *defaults
  caching:
    use: false

production:
  <<: *defaults
