defaults: &defaults
  caching:
    use: false

  author:
    name: Junya Ogura
    email: juno at sooey.com

  social:
    - name: links
      url: https://junya.bio.link/
    - name: qnyp
      url: https://qnyp.com/junya

  feedburner:
    use: true
    url: http://feeds.feedburner.com/Sooey

  google_custom_search:
    use: true
    code: 002120026113953543318:8wsc3jhy1fm

  twitter_anywhere:
    use: false
    id: ua931JjzNdqgvz2B0S85jA

development:
  <<: *defaults

test:
  <<: *defaults
  caching:
    use: false

production:
  <<: *defaults
