version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: circleci
      - image: circleci/postgres:12-alpine
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: ""
    working_directory: ~/jrnl
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-{{ .Environment.CACHE_KEY }}-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Installing Ruby Dependencies (bundler)
          command: |
            bundle config set clean "true"
            bundle config set path "vendor/bundle"
            bundle check || bundle install
      - save_cache:
          key: gem-cache-{{ .Environment.CACHE_KEY }}-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create db:schema:load
      - run:
          name: Test (rspec)
          command: bundle exec rails spec
