defaults: &defaults
  caching:
    use: false

  author:
    name: YOUR NAME
    email: YOUR ADDRESS

  social:
    - name: twitter
      url: https://twitter.com/YOURNAME
    - name: facebook
      url: https://facebook.com/YOURNAME

  feedburner:
    use: false
    url: FEED_ADDRESS

  google_custom_search:
    use: true
    code: CUSTOM_SEARCH_CODE

  typekit:
    use: true
    id: TYPEKIT_ID

  twitter_anywhere:
    use: true
    id: TWITTER_APP_ID

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
