defaults: &defaults
  caching:
    use: false

  author:
    name: Junya Ogura
    email: juno at sooey.com

  social:
    - name: qnyp
      url: https://qnyp.com/junya
    - name: twitter
      url: https://twitter.com/junya
    - name: pinboard
      url: https://pinboard.in/u:junya/
    - name: instagram
      url: https://www.instagram.com/junyaogura/

  feedburner:
    use: true
    url: http://feeds.feedburner.com/Sooey

  google_custom_search:
    use: true
    code: 002120026113953543318:8wsc3jhy1fm

  typekit:
    use: false
    id:

  twitter_anywhere:
    use: false
    id: ua931JjzNdqgvz2B0S85jA

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

  typekit:
    use: true
    id: ock6krn
