embed_assets: on
#package_assets: always

javascripts:
  common:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery.embedly.min.js
    - public/javascripts/rails.js
    - public/javascripts/application.js

stylesheets:
  common:
    - public/stylesheets/style.css
