common:
  author:
    name: Junya Ogura
    email: junyaogura@gmail.com

  social:
    - name: twitter
      url: http://twitter.com/junya
    - name: tumblr
      url: http://sooey.tumblr.com/
    - name: facebook
      url: http://facebook.com/junya.ogura
    - name: pinboard
      url: http://pinboard.in/u:junya/
    - name: flickr
      url: http://www.flickr.com/photos/sooey/
    - name: wishlist
      url: http://www.amazon.co.jp/wishlist/2VFJWLLDJF03B/

  feedburner:
    use: true
    url: http://feeds.feedburner.com/Sooey

  google_analytics:
    use: false
    code:

  google_custom_search:
    use: true
    code: 002120026113953543318:8wsc3jhy1fm

  observer_app:
    use: false
    code:

  typekit:
    use: false
    id:

  twitter_anywhere:
    use: true
    id: ua931JjzNdqgvz2B0S85jA

production:
  google_analytics:
    use: true
    code: UA-17293111-2

  observer_app:
    use: true
    code: 4c8dd5f1e697483134009cba

  typekit:
    use: true
    id: ock6krn

development:
