default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 2 } %>
  variables:
    statement_timeout: 5000

development:
  <<: *default
  database: jrnl_development

test:
  <<: *default
  database: jrnl_test
  min_messages: WARNING

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

