development:
  adapter: postgresql
  encoding: unicode
  database: jrnl_development
  pool: 5
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: jrnl_test
  pool: 5
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: jrnl_production
  pool: 5
